- hosts: all # You can also specify an IP address
  become: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_DEFAULT_REGION: "ap-southeast-1"
  vars: # Define new variables
#    BUDDY_EXECUTION_REVISION_SHOR: buddy
#    container_name: online_quiz
  tasks:
    - name: remove container
      ansible.builtin.shell:
        cmd: docker stop "{{container_name}}" || true && docker rm "{{container_name}}" || true
    - name: log in
      ansible.builtin.shell:
        cmd: aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 799941573255.dkr.ecr.ap-southeast-1.amazonaws.com/onlinequiz
    - name: download env 
      ansible.builtin.shell:
        cmd: aws s3 cp s3://smartjen-env/onlinecompetition/.env /etc/stg-sj-onlinequiz/.env
    - name: remove cache
      ansible.builtin.shell:
        cmd: rm -rf /var/www/html/bootstrap/cache/*        
    - name: run container
      ansible.builtin.shell:
        cmd: docker run -d --log-driver=awslogs --log-opt awslogs-region=ap-southeast-1 --log-opt awslogs-group=OnlineCompettionLogGroup --log-opt awslogs-create-group=true --name {{container_name}} --restart=always -v /etc/stg-sj-onlinequiz/.env:/var/www/html/.env -v /var/www/stg-sj-onlinequiz/html/storage:/var/www/html/storage:rw -v /var/www/stg-sj-onlinequiz/html/cache:/var/www/html/bootstrap/cache:rw -p 80:80 799941573255.dkr.ecr.ap-southeast-1.amazonaws.com/onlinequiz:{{ BUDDY_EXECUTION_REVISION_SHOR }} 
    - name: run config cache 
      ansible.builtin.shell:
        cmd: docker exec -it {{container_name}} php artisan config:cache   
    - name: run migrate 
      ansible.builtin.shell:
        cmd: docker exec -it {{container_name}} php artisan migrate --force
